export const INDUSTRIES = [
  "Abrasives and Nonmetallic Minerals Manufacturing",
  "Accessible Architecture and Design",
  "Accessible Hardware Manufacturing",
  "Accommodation and Food Services",
  "Accounting",
  "Administration of Justice",
  "Administrative and Support Services",
  "Advertising Services",
  "Agricultural Chemical Manufacturing",
  "Agriculture, Construction, Mining Machinery Manufacturing",
  "Air, Water, and Waste Program Management",
  "Airlines and Aviation",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Alternative Fuel Vehicle Manufacturing",
  "Alternative Medicine",
  "Ambulance Services",
  "Amusement Parks and Arcades",
  "Animal Feed Manufacturing",
  "Animation",
  "Animation and Post-production",
  "Apparel & Fashion",
  "Apparel Manufacturing",
  "Appliances, Electrical, and Electronics Manufacturing",
  "Architectural and Structural Metal Manufacturing",
  "Architecture & Planning",
  "Architecture and Planning",
  "Armed Forces",
  "Artificial Rubber and Synthetic Fiber Manufacturing",
  "Artists and Writers",
  "Arts & Crafts",
  "Audio and Video Equipment Manufacturing",
  "Automation Machinery Manufacturing",
  "Automotive",
  "Aviation & Aerospace",
  "Aviation and Aerospace Component Manufacturing",
  "Baked Goods Manufacturing",
  "Banking",
  "Bed-and-Breakfasts, Hostels, Homestays",
  "Beverage Manufacturing",
  "Biomass Electric Power Generation",
  "Biotechnology",
  "Biotechnology Research",
  "Blockchain Services",
  "Blogs",
  "Boilers, Tanks, and Shipping Container Manufacturing",
  "Book Publishing",
  "Book and Periodical Publishing",
  "Broadcast Media",
  "Broadcast Media Production and Distribution",
  "Building Construction",
  "Building Equipment Contractors",
  "Building Finishing Contractors",
  "Building Materials",
  "Building Structure and Exterior Contractors",
  "Business Consulting and Services",
  "Business Content",
  "Business Intelligence Platforms",
  "Business Supplies & Equipment",
  "Cable and Satellite Programming",
  "Capital Markets",
  "Caterers",
  "Chemical Manufacturing",
  "Chemical Raw Materials Manufacturing",
  "Chemicals",
  "Child Day Care Services",
  "Chiropractors",
  "Circuses and Magic Shows",
  "Civic & Social Organization",
  "Civic and Social Organizations",
  "Civil Engineering",
  "Claims Adjusting, Actuarial Services",
  "Clay and Refractory Products Manufacturing",
  "Climate Data and Analytics",
  "Climate Technology Product Manufacturing",
  "Coal Mining",
  "Collection Agencies",
  "Commercial Real Estate",
  "Commercial and Industrial Equipment Rental",
  "Commercial and Industrial Machinery Maintenance",
  "Commercial and Service Industry Machinery Manufacturing",
  "Communications Equipment Manufacturing",
  "Community Development and Urban Planning",
  "Community Services",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Hardware Manufacturing",
  "Computer Networking",
  "Computer Networking Products",
  "Computer Software",
  "Computer and Network Security",
  "Computers and Electronics Manufacturing",
  "Conservation Programs",
  "Construction",
  "Construction Hardware Manufacturing",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Goods Rental",
  "Consumer Services",
  "Correctional Institutions",
  "Cosmetics",
  "Cosmetology and Barber Schools",
  "Courts of Law",
  "Credit Intermediation",
  "Cutlery and Handtool Manufacturing",
  "Dairy",
  "Dairy Product Manufacturing",
  "Dance Companies",
  "Data Infrastructure and Analytics",
  "Data Security Software Products",
  "Death Care Services",
  "Defense & Space",
  "Defense and Space Manufacturing",
  "Dentists",
  "Design",
  "Design Services",
  "Desktop Computing Software Products",
  "Digital Accessibility Services",
  "E-Learning Providers",
  "E-learning",
  "Economic Programs",
  "Education",
  "Education Administration Programs",
  "Education Management",
  "Electric Lighting Equipment Manufacturing",
  "Electric Power Generation",
  "Electric Power Transmission, Control, and Distribution",
  "Electrical & Electronic Manufacturing",
  "Electrical Equipment Manufacturing",
  "Electronic and Precision Equipment Maintenance",
  "Embedded Software Products",
  "Emergency and Relief Services",
  "Energy Technology",
  "Engineering Services",
  "Engines and Power Transmission Equipment Manufacturing",
  "Entertainment",
  "Entertainment Providers",
  "Environmental Quality Programs",
  "Environmental Services",
  "Equipment Rental Services",
  "Events Services",
  "Executive Office",
  "Executive Search Services",
  "Fabricated Metal Products",
  "Facilities Services",
  "Family Planning Centers",
  "Farming",
  "Farming, Ranching, Forestry",
  "Fashion Accessories Manufacturing",
  "Financial Services",
  "Fine Art",
  "Fine Arts Schools",
  "Fire Protection",
  "Fishery",
  "Flight Training",
  "Food & Beverages",
  "Food Production",
  "Food and Beverage Manufacturing",
  "Food and Beverage Retail",
  "Food and Beverage Services",
  "Footwear Manufacturing",
  "Footwear and Leather Goods Repair",
  "Forestry and Logging",
  "Fossil Fuel Electric Power Generation",
  "Freight and Package Transportation",
  "Fruit and Vegetable Preserves Manufacturing",
  "Fuel Cell Manufacturing",
  "Fundraising",
  "Funds and Trusts",
  "Funeral Services",
  "Furniture",
  "Furniture and Home Furnishings Manufacturing",
  "Geothermal Electric Power Generation",
  "Glass Product Manufacturing",
  "Glass, Ceramics & Concrete",
  "Glass, Ceramics and Concrete Manufacturing",
  "Golf Courses and Country Clubs",
  "Government Administration",
  "Government Relations",
  "Government Relations Services",
  "Graphic Design",
  "Ground Passenger Transportation",
  "HVAC and Refrigeration Equipment Manufacturing",
  "Health and Human Services",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Highway, Street, and Bridge Construction",
  "Historical Sites",
  "Holding Companies",
  "Home Health Care Services",
  "Horticulture",
  "Hospital & Health Care",
  "Hospitality",
  "Hospitals",
  "Hospitals and Health Care",
  "Hotels and Motels",
  "Household Appliance Manufacturing",
  "Household Services",
  "Household and Institutional Furniture Manufacturing",
  "Housing Programs",
  "Housing and Community Development",
  "Human Resources",
  "Human Resources Services",
  "Hydroelectric Power Generation",
  "IT Services and IT Consulting",
  "IT System Custom Software Development",
  "IT System Data Services",
  "IT System Design Services",
  "IT System Installation and Disposal",
  "IT System Operations and Maintenance",
  "IT System Testing and Evaluation",
  "IT System Training and Support",
  "Import & Export",
  "Individual & Family Services",
  "Individual and Family Services",
  "Industrial Automation",
  "Industrial Machinery Manufacturing",
  "Industry Associations",
  "Information Services",
  "Information Technology & Services",
  "Insurance",
  "Insurance Agencies and Brokerages",
  "Insurance Carriers",
  "Insurance and Employee Benefit Funds",
  "Interior Design",
  "International Affairs",
  "International Trade & Development",
  "International Trade and Development",
  "Internet",
  "Internet Marketplace Platforms",
  "Internet News",
  "Internet Publishing",
  "Interurban and Rural Bus Services",
  "Investment Advice",
  "Investment Banking",
  "Investment Management",
  "Janitorial Services",
  "Judiciary",
  "Landscaping Services",
  "Language Schools",
  "Laundry and Drycleaning Services",
  "Law Enforcement",
  "Law Practice",
  "Leasing Non-residential Real Estate",
  "Leasing Residential Real Estate",
  "Leather Product Manufacturing",
  "Legal Services",
  "Legislative Office",
  "Leisure, Travel & Tourism",
  "Libraries",
  "Lime and Gypsum Products Manufacturing",
  "Loan Brokers",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Machinery Manufacturing",
  "Magnetic and Optical Media Manufacturing",
  "Management Consulting",
  "Manufacturing",
  "Maritime",
  "Maritime Transportation",
  "Market Research",
  "Marketing & Advertising",
  "Marketing Services",
  "Mattress and Blinds Manufacturing",
  "Measuring and Control Instrument Manufacturing",
  "Meat Products Manufacturing",
  "Mechanical Or Industrial Engineering",
  "Media Production",
  "Media and Telecommunications",
  "Medical Device",
  "Medical Equipment Manufacturing",
  "Medical Practice",
  "Medical Practices",
  "Medical and Diagnostic Laboratories",
  "Mental Health Care",
  "Metal Ore Mining",
  "Metal Treatments",
  "Metal Valve, Ball, and Roller Manufacturing",
  "Metalworking Machinery Manufacturing",
  "Military",
  "Military and International Affairs",
  "Mining",
  "Mining & Metals",
  "Mobile Computing Software Products",
  "Mobile Food Services",
  "Mobile Gaming Apps",
  "Motion Pictures & Film",
  "Motor Vehicle Manufacturing",
  "Motor Vehicle Parts Manufacturing",
  "Movies and Sound Recording",
  "Movies, Videos, and Sound",
  "Museums",
  "Museums & Institutions",
  "Museums, Historical Sites, and Zoos",
  "Nanotechnology",
  "Nanotechnology Research",
  "Natural Gas Distribution",
  "Natural Gas Extraction",
  "Newspaper Publishing",
  "Newspapers",
  "Non-profit Organization Management",
  "Non-profit Organizations",
  "Nonmetallic Mineral Mining",
  "Nonresidential Building Construction",
  "Nuclear Electric Power Generation",
  "Nursing Homes and Residential Care Facilities",
  "Office Furniture and Fixtures Manufacturing",
  "Oil & Energy",
  "Oil Extraction",
  "Oil and Coal Product Manufacturing",
  "Oil and Gas",
  "Oil, Gas, and Mining",
  "Online Audio and Video Media",
  "Online Media",
  "Online and Mail Order Retail",
  "Operations Consulting",
  "Optometrists",
  "Other Industries",
  "Outpatient Care Centers",
  "Outsourcing and Offshoring Consulting",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging & Containers",
  "Packaging and Containers Manufacturing",
  "Paint, Coating, and Adhesive Manufacturing",
  "Paper & Forest Products",
  "Paper and Forest Product Manufacturing",
  "Parts Distribution",
  "Pension Funds",
  "Performing Arts",
  "Performing Arts and Spectator Sports",
  "Periodical Publishing",
  "Personal Care Product Manufacturing",
  "Personal Care Services",
  "Personal and Laundry Services",
  "Pet Services",
  "Pharmaceutical Manufacturing",
  "Pharmaceuticals",
  "Philanthropic Fundraising Services",
  "Philanthropy",
  "Photography",
  "Physical, Occupational and Speech Therapists",
  "Physicians",
  "Pipeline Transportation",
  "Plastics",
  "Plastics Manufacturing",
  "Plastics and Rubber Product Manufacturing",
  "Political Organization",
  "Postal Services",
  "Primary Metal Manufacturing",
  "Primary and Secondary Education",
  "Primary/Secondary Education",
  "Printing",
  "Printing Services",
  "Professional Organizations",
  "Professional Services",
  "Professional Training & Coaching",
  "Professional Training and Coaching",
  "Program Development",
  "Public Assistance Programs",
  "Public Health",
  "Public Policy",
  "Public Policy Offices",
  "Public Relations & Communications",
  "Public Relations and Communications Services",
  "Public Safety",
  "Public Works",
  "Publishing",
  "Racetracks",
  "Radio and Television Broadcasting",
  "Rail Transportation",
  "Railroad Equipment Manufacturing",
  "Railroad Manufacture",
  "Ranching",
  "Ranching and Fisheries",
  "Real Estate",
  "Real Estate Agents and Brokers",
  "Real Estate and Equipment Rental Services",
  "Recreational Facilities",
  "Recreational Facilities & Services",
  "Regenerative Design",
  "Religious Institutions",
  "Renewable Energy Equipment Manufacturing",
  "Renewable Energy Power Generation",
  "Renewable Energy Semiconductor Manufacturing",
  "Renewables & Environment",
  "Repair and Maintenance",
  "Research",
  "Research Services",
  "Residential Building Construction",
  "Restaurants",
  "Retail",
  "Retail Apparel and Fashion",
  "Retail Appliances, Electrical, and Electronic Equipment",
  "Retail Art Dealers",
  "Retail Art Supplies",
  "Retail Books and Printed News",
  "Retail Building Materials and Garden Equipment",
  "Retail Florists",
  "Retail Furniture and Home Furnishings",
  "Retail Gasoline",
  "Retail Groceries",
  "Retail Health and Personal Care Products",
  "Retail Luxury Goods and Jewelry",
  "Retail Motor Vehicles",
  "Retail Office Equipment",
  "Retail Office Supplies and Gifts",
  "Retail Pharmacies",
  "Retail Recyclable Materials & Used Merchandise",
  "Reupholstery and Furniture Repair",
  "Robot Manufacturing",
  "Robotics Engineering",
  "Rubber Products Manufacturing",
  "Satellite Telecommunications",
  "Savings Institutions",
  "School and Employee Bus Services",
  "Seafood Product Manufacturing",
  "Secretarial Schools",
  "Securities and Commodity Exchanges",
  "Security & Investigations",
  "Security Guards and Patrol Services",
  "Security Systems Services",
  "Security and Investigations",
  "Semiconductors",
  "Services for Renewable Energy",
  "Services for the Elderly and Disabled",
  "Shipbuilding",
  "Shuttles and Special Needs Transportation Services",
  "Sightseeing Transportation",
  "Skiing Facilities",
  "Smart Meter Manufacturing",
  "Soap and Cleaning Product Manufacturing",
  "Social Networking Platforms",
  "Software Development",
  "Solar Electric Power Generation",
  "Sound Recording",
  "Space Research and Technology",
  "Specialty Trade Contractors",
  "Spectator Sports",
  "Sporting Goods",
  "Sporting Goods Manufacturing",
  "Sports",
  "Sports Teams and Clubs",
  "Sports and Recreation Instruction",
  "Spring and Wire Product Manufacturing",
  "Staffing & Recruiting",
  "Staffing and Recruiting",
  "Steam and Air-Conditioning Supply",
  "Strategic Management Services",
  "Subdivision of Land",
  "Sugar and Confectionery Product Manufacturing",
  "Supermarkets",
  "Surveying and Mapping Services",
  "Taxi and Limousine Services",
  "Technical and Vocational Training",
  "Technology, Information and Internet",
  "Technology, Information and Media",
  "Telecommunications",
  "Telecommunications Carriers",
  "Telephone Call Centers",
  "Temporary Help Services",
  "Textile Manufacturing",
  "Textiles",
  "Theater Companies",
  "Think Tanks",
  "Translation & Localization",
  "Translation and Localization",
  "Transportation Equipment Manufacturing",
  "Transportation Programs",
  "Transportation, Logistics, Supply Chain and Storage",
  "Transportation/Trucking/Railroad",
  "Travel Arrangements",
  "Truck Transportation",
  "Trusts and Estates",
  "Turned Products and Fastener Manufacturing",
  "Urban Transit Services",
  "Utilities",
  "Utility System Construction",
  "Vehicle Repair and Maintenance",
  "Venture Capital & Private Equity",
  "Venture Capital and Private Equity Principals",
  "Veterinary",
  "Veterinary Services",
  "Vocational Rehabilitation Services",
  "Warehousing",
  "Warehousing and Storage",
  "Waste Collection",
  "Waste Treatment and Disposal",
  "Water Supply and Irrigation Systems",
  "Water, Waste, Steam, and Air Conditioning Services",
  "Wellness and Fitness Services",
  "Wholesale",
  "Wholesale Apparel and Sewing Supplies",
  "Wholesale Appliances, Electrical, and Electronics",
  "Wholesale Building Materials",
  "Wholesale Chemical and Allied Products",
  "Wholesale Computer Equipment",
  "Wholesale Food and Beverage",
  "Wholesale Footwear",
  "Wholesale Furniture and Home Furnishings",
  "Wholesale Hardware, Plumbing, Heating Equipment",
  "Wholesale Import and Export",
  "Wholesale Luxury Goods and Jewelry",
  "Wholesale Machinery",
  "Wholesale Metals and Minerals",
  "Wholesale Motor Vehicles and Parts",
  "Wholesale Paper Products",
  "Wholesale Petroleum and Petroleum Products",
  "Wholesale Photography Equipment and Supplies",
  "Wholesale Raw Farm Products",
  "Wholesale Recyclable Materials",
  "Wind Electric Power Generation",
  "Wireless",
  "Wireless Services",
  "Women's Handbag Manufacturing",
  "Wood Product Manufacturing",
  "Writing & Editing",
  "Writing and Editing",
  "Zoos and Botanical Gardens"
];
