export const jobTitles = [
  "..",
  "...",
  ".NET Developer",
  "3D Artist",
  "3D Designer",
  "3D Visualizer",
  "ACCOUNTANT",
  "AI Engineer",
  "AVUKAT",
  "Account Assistant",
  "Account Director",
  "Account Executive",
  "Account Manager",
  "Account Officer",
  "Account Relationship Manager",
  "Account Specialist",
  "Accountant",
  "Accounting",
  "Accounting Assistant",
  "Accounting Clerk",
  "Accounting Intern",
  "Accounting Manager",
  "Accounting Specialist",
  "Accounting Supervisor",
  "Accounts Assistant",
  "Accounts Manager",
  "Accounts Payable Accountant",
  "Accounts Payable Specialist",
  "Accounts Receivable Accountant",
  "Active Member",
  "Actor",
  "Adjoint administratif",
  "Admin",
  "Admin Assistant",
  "Administrateur",
  "Administration",
  "Administration Assistant",
  "Administration Manager",
  "Administrative",
  "Administrative Aide",
  "Administrative Assistant",
  "Administrative Clerk",
  "Administrative Coordinator",
  "Administrative Manager",
  "Administrative Officer",
  "Administrative Secretary",
  "Administrative Specialist",
  "Administrative Supervisor",
  "Administrator",
  "Advisor",
  "Advocate",
  "Agent",
  "Agent administratif",
  "Agent commercial",
  "Agricultural Engineer",
  "Aide-comptable",
  "Air Traffic Controller",
  "Aircraft Maintenance Engineer",
  "Aircraft Maintenance Technician",
  "Aircraft Mechanic",
  "Aircraft Technician",
  "Airline Pilot",
  "Ambassador",
  "Analyst",
  "Analytical Chemist",
  "Android Developer",
  "Anesthesia Technician",
  "Anesthesiologist",
  "Animator",
  "Application Developer",
  "Application Engineer",
  "Arabic Teacher",
  "Arbeidsgiver",
  "Architect",
  "Architecte",
  "Architectural Designer",
  "Architectural Draftsman",
  "Architectural Engineer",
  "Architectural Intern",
  "Architecture",
  "Area Manager",
  "Area Sales Manager",
  "Area Sales Supervisor",
  "Art Director",
  "Art Teacher",
  "Article Assistant",
  "Artist",
  "Asistan",
  "Assistant",
  "Assistant Accountant",
  "Assistant Auditor",
  "Assistant Branch Manager",
  "Assistant Chef",
  "Assistant Director",
  "Assistant Engineer",
  "Assistant Front Office Manager",
  "Assistant General Manager",
  "Assistant Lecturer",
  "Assistant Manager",
  "Assistant Manager Finance",
  "Assistant Manager Human Resources",
  "Assistant Marketing Manager",
  "Assistant Operations Manager",
  "Assistant Professor",
  "Assistant Project Manager",
  "Assistant Relationship Manager",
  "Assistant Restaurant Manager",
  "Assistant Sales Manager",
  "Assistant Specialist",
  "Assistant Store Manager",
  "Assistant Supervisor",
  "Assistant Vice President",
  "Assistant commercial",
  "Assistant comptable",
  "Assistant direction",
  "Assistante",
  "Assistante administrative",
  "Assistante commerciale",
  "Assistante comptable",
  "Assistante de direction",
  "Associate",
  "Associate Consultant",
  "Associate Director",
  "Associate Professor",
  "Attorney",
  "Attorney At Law",
  "Audit Assistant",
  "Audit Associate",
  "Audit Intern",
  "Audit Manager",
  "Audit Senior",
  "Audit Supervisor",
  "Auditor",
  "Autocad Draftsman",
  "Automation Engineer",
  "Automotive Service Advisor",
  "Automotive Technician",
  "Avocat",
  "Avukat",
  "BIM Architect",
  "BIM Modeler",
  "Back End Developer",
  "Back Office Employee",
  "Back-end Developer",
  "Backend Developer",
  "Baker",
  "Bank Employee",
  "Bank Teller",
  "Banker",
  "Banking",
  "Bar Manager",
  "Bar Waiter",
  "Barber",
  "Barista",
  "Barman",
  "Barmen",
  "Bartender",
  "Beauty Advisor",
  "Biologist",
  "Biology Teacher",
  "Biomedical Engineer",
  "Biyolog",
  "Blogger",
  "Board Member",
  "Bookkeeper",
  "Boss",
  "Branch Manager",
  "Branch Supervisor",
  "Brand Ambassador",
  "Brand Manager",
  "Broker",
  "Bus Driver",
  "Business",
  "Business Analyst",
  "Business Consultant",
  "Business Developer",
  "Business Development",
  "Business Development Associate",
  "Business Development Consultant",
  "Business Development Director",
  "Business Development Executive",
  "Business Development Intern",
  "Business Development Manager",
  "Business Development Officer",
  "Business Development Specialist",
  "Business Intelligence Developer",
  "Business Manager",
  "Business Owner",
  "Business Partner",
  "Business Specialist",
  "Business Unit Manager",
  "Buyer",
  "CCTV Operator",
  "CEO",
  "CEO & Founder",
  "CFO",
  "COO",
  "CTO",
  "Cabin Crew",
  "Caissier",
  "Call Agent",
  "Call Center Agent",
  "Call Center Customer Service Representative",
  "Call Center Representative",
  "Call Center Specialist",
  "Call Center Supervisor",
  "Candidate Engineer",
  "Captain",
  "Captain Waiter",
  "Car Driver",
  "Career Break",
  "Caregiver",
  "Carpenter",
  "Cashier",
  "Cashier Customer Service",
  "Category Manager",
  "Ceo",
  "Certified Nursing Assistant",
  "Chairman",
  "Chairman Of The Board",
  "Chairman of the Board",
  "Charge Nurse",
  "Chauffeur",
  "Chauffeur livreur",
  "Chef",
  "Chef De Cuisine",
  "Chef De Partie",
  "Chef d'entreprise",
  "Chef de Partie",
  "Chef de chantier",
  "Chef de partie",
  "Chef de projet",
  "Chef de rang",
  "Chef de service",
  "Chemical Engineer",
  "Chemist",
  "Chemistry Teacher",
  "Chief Accountant",
  "Chief Engineer",
  "Chief Executive Officer",
  "Chief Financial Officer",
  "Chief Marketing Officer",
  "Chief Officer",
  "Chief Operating Officer",
  "Chief Operations Officer",
  "Chief Technology Officer",
  "Civil Engineer",
  "Civil Engineering Intern",
  "Civil Engineering Professional",
  "Civil Project Engineer",
  "Civil Structural Engineer",
  "Civil Supervisor",
  "Class Teacher",
  "Cleaner",
  "Clerk",
  "Client Advisor",
  "Clinical Dietitian",
  "Clinical Pharmacist",
  "Clinical Psychologist",
  "Clinical Psychology Intern",
  "Co Founder",
  "Co-Founder",
  "Co-Founder & CEO",
  "Co-Owner",
  "Coach",
  "Collections Specialist",
  "Commercial",
  "Commercial Director",
  "Commercial Manager",
  "Commercial Specialist",
  "Commerciale",
  "Commi 1",
  "Commi chef",
  "Commis",
  "Commis 1",
  "Commis Chef",
  "Commission Sales Associate",
  "Commissioning Engineer",
  "Communications Specialist",
  "Community Manager",
  "Community Pharmacist",
  "Community pharmacist",
  "Company Driver",
  "Company Owner",
  "Compliance Officer",
  "Comptable",
  "Computer Engineer",
  "Computer Numerical Control Machinist",
  "Computer Numerical Control Programmer",
  "Computer Operator",
  "Computer Programmer",
  "Computer Science Teacher",
  "Computer Teacher",
  "Computer Technician",
  "Concierge",
  "Conducteur de travaux",
  "Conseiller client",
  "Conseiller commercial",
  "Conseiller ventes",
  "Construction Engineer",
  "Construction Manager",
  "Construction Project Manager",
  "Construction Supervisor",
  "Consultant",
  "Contact Center Agent",
  "Content Creator",
  "Content Editor",
  "Content Manager",
  "Content Moderator",
  "Content Specialist",
  "Content Writer",
  "Contract Manager",
  "Contract Specialist",
  "Contractor",
  "Control Room Operator",
  "Controller",
  "Cook",
  "Coordinator",
  "Copywriter",
  "Cost Accountant",
  "Cost Control Engineer",
  "Cost Controller",
  "Counselor",
  "Country Manager",
  "Course Instructor",
  "Crane Operator",
  "Creative Designer",
  "Creative Director",
  "Credit Analyst",
  "Credit Controller",
  "Credit Officer",
  "Crew Member",
  "Cuisinier",
  "Customer Advisor",
  "Customer Care Executive",
  "Customer Care Representative",
  "Customer Relations Manager",
  "Customer Relations Officer",
  "Customer Relations Specialist",
  "Customer Relationship Management Specialist",
  "Customer Representative",
  "Customer Service",
  "Customer Service Advisor",
  "Customer Service Agent",
  "Customer Service Assistant",
  "Customer Service Associate",
  "Customer Service Executive",
  "Customer Service Manager",
  "Customer Service Officer",
  "Customer Service Representative",
  "Customer Service Specialist",
  "Customer Service Staff",
  "Customer Service Supervisor",
  "Customer Service Team Lead",
  "Customer Services Agent",
  "Customer Services Specialist",
  "Customer Success Manager",
  "Customer Support Engineer",
  "Customer Support Specialist",
  "Customer service",
  "Cyber Security Analyst",
  "Cyber Security Engineer",
  "Cyber Security Specialist",
  "Data Analyst",
  "Data Engineer",
  "Data Entry",
  "Data Entry Clerk",
  "Data Entry Operator",
  "Data Entry Specialist",
  "Data Science Intern",
  "Data Scientist",
  "Data entry",
  "Database Administrator",
  "Debt Collector",
  "Deck Cadet",
  "Delegate",
  "Delivery Driver",
  "Demi Chef De Partie",
  "Demi chef",
  "Demonstrator",
  "Dental Assistant",
  "Dental Intern",
  "Dentist",
  "Department Manager",
  "Depo Sorumlusu",
  "Deputy CEO",
  "Deputy General Manager",
  "Deputy Manager",
  "Deputy Project Manager",
  "Dermatologist",
  "Design Architect",
  "Design Engineer",
  "Design Manager",
  "Designer",
  "DevOps Engineer",
  "Developer",
  "Development Manager",
  "Development Team Lead",
  "Dietetic Intern",
  "Dietitian",
  "Digital Marketing Consultant",
  "Digital Marketing Executive",
  "Digital Marketing Intern",
  "Digital Marketing Manager",
  "Digital Marketing Specialist",
  "Directeur",
  "Directeur commercial",
  "Directeur technique",
  "Director",
  "Director General",
  "Director Of Operations",
  "Director of Business Development",
  "Director of Finance",
  "Director of Operations",
  "Dispatcher",
  "District Manager",
  "District Sales Manager",
  "Diyetisyen",
  "Doctor",
  "Document Controller",
  "Doktor",
  "Dr",
  "Dr.",
  "Draftsman",
  "Driller",
  "Drilling Engineer",
  "Driver",
  "Duty Manager",
  "Ecommerce Manager",
  "Ecommerce Specialist",
  "Economist",
  "Editor",
  "Educational Consultant",
  "Educator",
  "Electric Engineer",
  "Electrical Design Engineer",
  "Electrical Electronic Engineer",
  "Electrical Engineer",
  "Electrical Engineering Intern",
  "Electrical Foreman",
  "Electrical Maintenance Engineer",
  "Electrical Project Engineer",
  "Electrical Site Engineer",
  "Electrical Supervisor",
  "Electrical Technician",
  "Electrician",
  "Electronic Engineer",
  "Electronic Technician",
  "Elektrik Elektronik Teknikeri",
  "Elektrik Teknikeri",
  "Elektrik Teknisyeni",
  "Elektrik teknikeri",
  "Elementary School Teacher",
  "Embedded Software Engineer",
  "Emekli",
  "Emergency Medical Technician",
  "Emergency Medicine Physician",
  "Emergency Room Nurse",
  "Employee",
  "Employer",
  "Engineer",
  "Engineer Intern",
  "Engineering Intern",
  "Engineering Manager",
  "Engineering Supervisor",
  "Engineering Trainee",
  "English Instructor",
  "English Language Instructor",
  "English Language Teacher",
  "English Second Language Instructor",
  "English Second Language Teacher",
  "English Teacher",
  "English Translator",
  "English Tutor",
  "English teacher",
  "Enseignant",
  "Enseignante",
  "Entrepreneur",
  "Environment, Health and Safety Manager",
  "Environmental Engineer",
  "Environmental Health Safety Specialist",
  "Esnaf",
  "Estimation Engineer",
  "Event Coordinator",
  "Event Manager",
  "Event Organizer",
  "Event Planner",
  "Executive",
  "Executive Administrative Assistant",
  "Executive Assistant",
  "Executive Chef",
  "Executive Director",
  "Executive Housekeeper",
  "Executive Manager",
  "Executive Secretary",
  "Executive Sous Chef",
  "Expert",
  "Export Manager",
  "Export Sales Manager",
  "Export Specialist",
  "External Auditor",
  "Facilities Engineer",
  "Facilities Manager",
  "Factory Manager",
  "Faculty Lecturer",
  "Faculty Member",
  "Fashion Designer",
  "Fellow",
  "Field Engineer",
  "Field Operator",
  "Field Service Engineer",
  "Field Services Engineer",
  "Filmmaker",
  "Finance",
  "Finance Assistant",
  "Finance Director",
  "Finance Executive",
  "Finance Intern",
  "Finance Manager",
  "Finance Officer",
  "Finance Specialist",
  "Financial Accountant",
  "Financial Advisor",
  "Financial Analyst",
  "Financial Auditor",
  "Financial Consultant",
  "Financial Controller",
  "Financial Manager",
  "Finans",
  "Firefighter",
  "Firma Sahibi",
  "First Officer",
  "Fitness Coach",
  "Fitness Instructor",
  "Fitness Trainer",
  "Fizyoterapist",
  "Flight Attendant",
  "Floor Manager",
  "Floor Supervisor",
  "Flutter Developer",
  "Fonctionnaire",
  "Fondateur",
  "Food And Beverage Assistant",
  "Food And Beverage Attendant",
  "Food And Beverage Supervisor",
  "Food Engineer",
  "Food Server",
  "Food Service Worker",
  "Food and Beverage Manager",
  "Food and Beverage Server",
  "Food and Beverage Specialist",
  "Football Coach",
  "Football Player",
  "Foreign Trade Manager",
  "Foreign Trade Specialist",
  "Foreman",
  "Forklift Operator",
  "Formateur",
  "Formen",
  "Founder",
  "Founder & CEO",
  "Founder and CEO",
  "Founding Partner",
  "Freelance",
  "Freelance Consultant",
  "Freelance Designer",
  "Freelance Graphic Designer",
  "Freelance Interior Designer",
  "Freelance Photographer",
  "Freelance Translator",
  "Freelance Video Editor",
  "Freelance Web Developer",
  "Freelance Writer",
  "Freelancer",
  "French Teacher",
  "Fresher",
  "Front Desk Agent",
  "Front Desk Receptionist",
  "Front Office Agent",
  "Front Office Executive",
  "Front Office Manager",
  "Front Office Receptionist",
  "Front Office Supervisor",
  "Frontend Developer",
  "Frontend Web Developer",
  "Full Stack Developer",
  "Full Stack Engineer",
  "Full-stack Developer",
  "GERANT",
  "GM",
  "Game Developer",
  "Garson",
  "General Accountant",
  "General Coordinator",
  "General Dental Practitioner",
  "General Dentist",
  "General Manager",
  "General Practitioner",
  "General manager",
  "Geologist",
  "Geotechnical Engineer",
  "Gerant",
  "German Teacher",
  "Gestionnaire",
  "Graduate",
  "Graduate Engineering Trainee",
  "Graduate Research Assistant",
  "Graduate Student",
  "Graduate Teaching Assistant",
  "Graduate Trainee",
  "Graduation Project",
  "Grafiker",
  "Graphic Design Artist",
  "Graphic Design Intern",
  "Graphic Design Specialist",
  "Graphic Designer",
  "Graphic designer",
  "Graphiste",
  "Group CEO",
  "Guest Relations Agent",
  "Guest Relations Officer",
  "Guest Service Agent",
  "Guest Services Associate",
  "HR",
  "HR Assistant",
  "HR Business Partner",
  "HR Coordinator",
  "HR Executive",
  "HR Generalist",
  "HR Manager",
  "HR Officer",
  "HR Recruiter",
  "HR Specialist",
  "HSE",
  "HSE Advisor",
  "HSE Engineer",
  "HSE Manager",
  "HSE Officer",
  "HSE Supervisor",
  "HVAC Engineer",
  "Hairstylist",
  "Hardware Engineer",
  "Harita Teknikeri",
  "Head",
  "Head Bartender",
  "Head Cashier",
  "Head Chef",
  "Head Of Department",
  "Head Of Operations",
  "Head Teller",
  "Head Waiter",
  "Head of Department",
  "Head of Human Resources",
  "Head of Marketing",
  "Head of Operations",
  "Head of Sales",
  "Head of Section",
  "Health And Safety Officer",
  "Health Safety Environment Engineer",
  "Health Safety Environment Officer",
  "Health Safety Environment Supervisor",
  "Healthcare Assistant",
  "Heating Air Conditioning Technician",
  "Heating And Air Conditioning Engineer",
  "Help Desk Specialist",
  "Homemaker",
  "Hospital Pharmacist",
  "Host",
  "Hostess",
  "Hotel Manager",
  "Hotel Receptionist",
  "House Officer",
  "Housekeeper",
  "Housekeeping",
  "Housekeeping Attendant",
  "Housekeeping Specialist",
  "Housekeeping Supervisor",
  "Housewife",
  "Human Resources",
  "Human Resources Administrator",
  "Human Resources Assistant",
  "Human Resources Business Partner",
  "Human Resources Consultant",
  "Human Resources Coordinator",
  "Human Resources Director",
  "Human Resources Executive",
  "Human Resources Generalist",
  "Human Resources Intern",
  "Human Resources Management",
  "Human Resources Manager",
  "Human Resources Officer",
  "Human Resources Recruiter",
  "Human Resources Specialist",
  "Human Resources Supervisor",
  "Human Resources Trainee",
  "IT",
  "IT Administrator",
  "IT Consultant",
  "IT Engineer",
  "IT Intern",
  "IT Manager",
  "IT Project Manager",
  "IT Specialist",
  "IT Support",
  "IT Support Engineer",
  "IT Support Specialist",
  "IT Support Technician",
  "IT Technician",
  "Import Export Manager",
  "Import Export Specialist",
  "Import Specialist",
  "Income Auditor",
  "Independent Consultant",
  "Industrial Designer",
  "Industrial Engineer",
  "Industrial Engineering Intern",
  "Industrial Trainee",
  "Infirmier",
  "Infographiste",
  "Information Technology",
  "Information Technology Administrator",
  "Information Technology Consultant",
  "Information Technology Engineer",
  "Information Technology Help Desk",
  "Information Technology Intern",
  "Information Technology Manager",
  "Information Technology Specialist",
  "Information Technology Support Engineer",
  "Information Technology Support Specialist",
  "Inspection Engineer",
  "Inspector",
  "Instructor",
  "Instrument Engineer",
  "Instrument Supervisor",
  "Instrument Technician",
  "Instrumentation Engineer",
  "Instrumentation and Control Engineer",
  "Insurance Agent",
  "Insurance Coordinator",
  "Insurance Specialist",
  "Intensive Care Nurse",
  "Interior Architect",
  "Interior Design Intern",
  "Interior Designer",
  "Intern",
  "Internal Audit Manager",
  "Internal Auditor",
  "Internee",
  "Internship",
  "Internship Trainee",
  "Interpreter",
  "Inventory Controller",
  "Investment Analyst",
  "Investment Manager",
  "Investor",
  "Java Developer",
  "Jewelry Designer",
  "Journalist",
  "Journaliste",
  "Junior Accountant",
  "Junior Architect",
  "Junior Associate",
  "Junior Engineer",
  "Junior Graphic Designer",
  "Junior Interior Designer",
  "Junior Lawyer",
  "Junior Software Developer",
  "Junior Software Engineer",
  "Junior Sous Chef",
  "Kalite Kontrol",
  "Kalite Kontrol Sorumlusu",
  "Kasiyer",
  "Key Account Executive",
  "Key Account Manager",
  "Kimyager",
  "Kindergarten Teacher",
  "Kitchen Staff",
  "Kitchen Steward",
  "Klinik Psikolog",
  "Komi",
  "Kurucu",
  "Kurucu Ortak",
  "Kurye",
  "Laboratory Assistant",
  "Laboratory Intern",
  "Laboratory Manager",
  "Laboratory Specialist",
  "Laboratory Technician",
  "Land Surveyor",
  "Landscape Architect",
  "Law Intern",
  "Lawyer",
  "Lead Engineer",
  "Lead Software Engineer",
  "Learning Support Assistant",
  "Lecturer",
  "Legal Advisor",
  "Legal Assistant",
  "Legal Associate",
  "Legal Consultant",
  "Legal Counsel",
  "Legal Intern",
  "Legal Researcher",
  "Legal Specialist",
  "Legal Trainee",
  "Librarian",
  "Lifeguard",
  "Line Cook",
  "Logistics",
  "Logistics Assistant",
  "Logistics Coordinator",
  "Logistics Executive",
  "Logistics Manager",
  "Logistics Officer",
  "Logistics Specialist",
  "Logistics Supervisor",
  "Lojistik",
  "Long Term Intern",
  "MANAGER",
  "MD",
  "MEP Engineer",
  "MEP Project Manager",
  "MEP Supervisor",
  "MUHASEBE",
  "Machine Learning Engineer",
  "Machine Operator",
  "Magasinier",
  "Maintenance",
  "Maintenance Electrician",
  "Maintenance Engineer",
  "Maintenance Manager",
  "Maintenance Supervisor",
  "Maintenance Technician",
  "Makeup Artist",
  "Management",
  "Management Accountant",
  "Management Consultant",
  "Management Trainee",
  "Manager",
  "Manager of Sales",
  "Managing Director",
  "Managing Partner",
  "Manger",
  "Manufacturing Engineer",
  "Marine Engineer",
  "Marketer",
  "Marketing",
  "Marketing And Public Relations Specialist",
  "Marketing Assistant",
  "Marketing Consultant",
  "Marketing Coordinator",
  "Marketing Director",
  "Marketing Executive",
  "Marketing Intern",
  "Marketing Manager",
  "Marketing Officer",
  "Marketing Specialist",
  "Marketing Staff",
  "Marketing Supervisor",
  "Marketing Team",
  "Marketing Team Member",
  "Massage Therapist",
  "Master",
  "Masters Student",
  "Math Teacher",
  "Mathematics Teacher",
  "Mechanic",
  "Mechanical Design Engineer",
  "Mechanical Designer",
  "Mechanical Engineer",
  "Mechanical Engineering Intern",
  "Mechanical Maintenance Engineer",
  "Mechanical Project Engineer",
  "Mechanical Site Engineer",
  "Mechanical Supervisor",
  "Mechanical Technician",
  "Mechatronics Engineer",
  "Media Buyer",
  "Media Manager",
  "Media Specialist",
  "Medical Coder",
  "Medical Director",
  "Medical Doctor",
  "Medical Intern",
  "Medical Laboratory Technician",
  "Medical Laboratory Technologist",
  "Medical Officer",
  "Medical Receptionist",
  "Medical Representative",
  "Medical Sales Representative",
  "Medical Secretary",
  "Medical Student",
  "Mekanik Teknisyeni",
  "Member",
  "Membre",
  "Memur",
  "Mentor",
  "Merchandiser",
  "Microbiologist",
  "Midwife",
  "Mimar",
  "Mining Engineer",
  "Mobile Application Developer",
  "Mobile Developer",
  "Model",
  "Moderator",
  "Motion Graphic Designer",
  "Muhabir",
  "Muhasebe",
  "Muhasebe Personeli",
  "Muhasebe Sorumlusu",
  "Muhasebe Stajyeri",
  "Muhasebeci",
  "Music Producer",
  "Music Teacher",
  "Musician",
  "NDT Inspector",
  "NDT Technician",
  "Nanny",
  "National Sales Manager",
  "Network Administrator",
  "Network Engineer",
  "Network Security Engineer",
  "Network Specialist",
  "Network Technician",
  "News Editor",
  "Night Auditor",
  "Night Manager",
  "None",
  "Nurse",
  "Nurse Intern",
  "Nutritionist",
  "Occupational Health and Safety Specialist",
  "Occupational Therapist",
  "Office Administrator",
  "Office Assistant",
  "Office Associate",
  "Office Boy",
  "Office Coordinator",
  "Office Manager",
  "Office Staff",
  "Officer",
  "Operasyon",
  "Operasyon Sorumlusu",
  "Operation",
  "Operation Engineer",
  "Operation Manager",
  "Operation Supervisor",
  "Operational Specialist",
  "Operations",
  "Operations Assistant",
  "Operations Coordinator",
  "Operations Engineer",
  "Operations Executive",
  "Operations Manager",
  "Operations Officer",
  "Operations Specialist",
  "Operations Supervisor",
  "Operations Team Member",
  "Operator",
  "Ophthalmologist",
  "Optometrist",
  "Oracle Developer",
  "Organization Manager",
  "Organizer",
  "Ortak Kurucu",
  "Orthodontist",
  "Orthopaedic Surgeon",
  "Owner",
  "PDG",
  "PHD",
  "PHD Student",
  "PHP Developer",
  "Painter",
  "Paralegal",
  "Paramedic",
  "Participant",
  "Partner",
  "Passenger Service Agent",
  "Pastry Chef",
  "Patron",
  "Payroll Specialist",
  "Pazarlama",
  "Pediatrician",
  "Penetration Tester",
  "Personal Assistant",
  "Personal Banker",
  "Personal Trainer",
  "Petroleum Engineer",
  "Pharmacien",
  "Pharmacist",
  "Pharmacist Assistant",
  "Pharmacy Assistant",
  "Pharmacy Intern",
  "Pharmacy Manager",
  "Pharmacy Technician",
  "Photographer",
  "Physical Education Teacher",
  "Physical Therapist",
  "Physician",
  "Physics Teacher",
  "Physiotherapist",
  "Pilot",
  "Pipefitter",
  "Piping Engineer",
  "Piping Supervisor",
  "Planner",
  "Planning Engineer",
  "Planning Manager",
  "Planning Specialist",
  "Plant Manager",
  "Plant Operator",
  "Plumber",
  "Police Officer",
  "Portfolio Manager",
  "Postdoctoral Researcher",
  "Presales Engineer",
  "Preschool Teacher",
  "President",
  "Primary School Teacher",
  "Principal",
  "Private Tutor",
  "Process Associate",
  "Process Engineer",
  "Procurement Assistant",
  "Procurement Coordinator",
  "Procurement Engineer",
  "Procurement Executive",
  "Procurement Manager",
  "Procurement Officer",
  "Procurement Specialist",
  "Producer",
  "Product Designer",
  "Product Engineer",
  "Product Manager",
  "Product Marketing Manager",
  "Product Owner",
  "Product Specialist",
  "Production Assistant",
  "Production Coordinator",
  "Production Engineer",
  "Production Intern",
  "Production Manager",
  "Production Operator",
  "Production Planner",
  "Production Planning Engineer",
  "Production Specialist",
  "Production Supervisor",
  "Prof. Dr.",
  "Professeur",
  "Professional Driver",
  "Professional Freelancer",
  "Professional Medical Representative",
  "Professional Photographer",
  "Professional development",
  "Professor",
  "Program Coordinator",
  "Program Manager",
  "Programmer",
  "Project Architect",
  "Project Assistant",
  "Project Control Engineer",
  "Project Coordinator",
  "Project Development Manager",
  "Project Director",
  "Project Engineer",
  "Project Intern",
  "Project Lead",
  "Project Leader",
  "Project Management Intern",
  "Project Management Officer",
  "Project Management Specialist",
  "Project Manager",
  "Project Officer",
  "Project Specialist",
  "Project Supervisor",
  "Project coordinator",
  "Project manager",
  "Projects Manager",
  "Promoter",
  "Property Advisor",
  "Property Consultant",
  "Property Manager",
  "Psikolog",
  "Psychologist",
  "Psychology Intern",
  "Psychotherapist",
  "Public Relations",
  "Public Relations Intern",
  "Public Relations Manager",
  "Public Relations Officer",
  "Public Relations Specialist",
  "Purchase Manager",
  "Purchase Officer",
  "Purchase Specialist",
  "Purchaser",
  "Purchasing Assistant",
  "Purchasing Manager",
  "Purchasing Officer",
  "Purchasing Specialist",
  "Python Developer",
  "QA Engineer",
  "QA Manager",
  "QA/QC",
  "QA/QC Engineer",
  "QA/QC Inspector",
  "QA/QC Manager",
  "QC Engineer",
  "QC Inspector",
  "Quality Analyst",
  "Quality Assurance",
  "Quality Assurance Engineer",
  "Quality Assurance Manager",
  "Quality Assurance Officer",
  "Quality Assurance Quality Control",
  "Quality Assurance Quality Control Engineer",
  "Quality Assurance Specialist",
  "Quality Control",
  "Quality Control Analyst",
  "Quality Control Engineer",
  "Quality Control Inspector",
  "Quality Control Intern",
  "Quality Control Manager",
  "Quality Control Specialist",
  "Quality Control Supervisor",
  "Quality Controller",
  "Quality Engineer",
  "Quality Inspector",
  "Quality Manager",
  "Quality Specialist",
  "Quantity Surveyor",
  "R&D Engineer",
  "R&D Manager",
  "Radiographer",
  "Radiologic Technologist",
  "Radiologist",
  "Radiology Technician",
  "Radiology Technologist",
  "Real Estate Agent",
  "Real Estate Broker",
  "Real Estate Consultant",
  "Real Estate Sales",
  "Real Estate Specialist",
  "Receptionist",
  "Recruiter",
  "Recruitment Consultant",
  "Recruitment Coordinator",
  "Recruitment Manager",
  "Recruitment Officer",
  "Recruitment Specialist",
  "Regional Director",
  "Regional Manager",
  "Regional Sales Manager",
  "Registered Nurse",
  "Regulatory Affairs Specialist",
  "Relationship Manager",
  "Relationship Officer",
  "Reporter",
  "Representative",
  "Research Analyst",
  "Research And Development Engineer",
  "Research And Development Intern",
  "Research And Development Specialist",
  "Research Assistant",
  "Research Associate",
  "Research Fellow",
  "Research Intern",
  "Researcher",
  "Resepsiyonist",
  "Reservations Agent",
  "Reservations Manager",
  "Resident Doctor",
  "Resident Engineer",
  "Respiratory Therapist",
  "Responsable RH",
  "Responsable adjoint",
  "Responsable administratif",
  "Responsable commercial",
  "Responsable de magasin",
  "Responsable de production",
  "Responsable de projet",
  "Responsable des ressources humaines",
  "Responsable des ventes",
  "Responsable logistique",
  "Responsable maintenance",
  "Responsable marketing",
  "Responsable technique",
  "Restaurant General Manager",
  "Restaurant Manager",
  "Restaurant Supervisor",
  "Retail Cashier",
  "Retail Manager",
  "Retail Sales Associate",
  "Retail Sales Manager",
  "Retail Sales Representative",
  "Retail Sales Specialist",
  "Retail Salesperson",
  "Retail Store Manager",
  "Retired",
  "Rigger",
  "Room Attendant",
  "Room Service Waiter",
  "SMMM",
  "SOC Analyst",
  "STAJYER",
  "Safety Engineer",
  "Safety Officer",
  "Safety Specialist",
  "Safety Supervisor",
  "Sahip",
  "Sales",
  "Sales & Marketing Manager",
  "Sales Account Manager",
  "Sales Administrator",
  "Sales Advisor",
  "Sales Advocate",
  "Sales Agent",
  "Sales And Marketing Intern",
  "Sales And Marketing Representative",
  "Sales And Marketing Specialist",
  "Sales Assistant",
  "Sales Associate",
  "Sales Attendant",
  "Sales Cashier",
  "Sales Consultant",
  "Sales Coordinator",
  "Sales Department",
  "Sales Development Representative",
  "Sales Director",
  "Sales Employee",
  "Sales Engineer",
  "Sales Executive",
  "Sales Expert",
  "Sales Intern",
  "Sales Manager",
  "Sales Marketing Executive",
  "Sales Marketing Manager",
  "Sales Merchandiser",
  "Sales Officer",
  "Sales Professional",
  "Sales Promoter",
  "Sales Representative",
  "Sales Specialist",
  "Sales Staff",
  "Sales Supervisor",
  "Sales Support Specialist",
  "Sales Team Lead",
  "Sales Team Leader",
  "Sales and Marketing Manager",
  "Sales man",
  "Sales manager",
  "Salesman",
  "Salesperson",
  "Saleswoman",
  "Sans emploi",
  "Sans-emploi",
  "Science Teacher",
  "Scientific Researcher",
  "Scrum Master",
  "Search Engine Optimization Specialist",
  "Secretary",
  "Secretary General",
  "Section Manager",
  "Security",
  "Security Guard",
  "Security Manager",
  "Security Officer",
  "Security Professional",
  "Security Supervisor",
  "Sekreter",
  "Self Employed",
  "Seller",
  "Senior",
  "Senior Account Executive",
  "Senior Account Manager",
  "Senior Accountant",
  "Senior Analyst",
  "Senior Architect",
  "Senior Art Director",
  "Senior Associate",
  "Senior Auditor",
  "Senior Business Analyst",
  "Senior Business Development Manager",
  "Senior Buyer",
  "Senior Civil Engineer",
  "Senior Consultant",
  "Senior Customer Service Representative",
  "Senior Data Analyst",
  "Senior Design Engineer",
  "Senior Designer",
  "Senior Developer",
  "Senior Document Controller",
  "Senior Electrical Engineer",
  "Senior Electrical Technician",
  "Senior Engineer",
  "Senior Executive",
  "Senior Financial Accountant",
  "Senior Financial Analyst",
  "Senior Frontend Developer",
  "Senior Graphic Designer",
  "Senior Human Resources Specialist",
  "Senior Interior Designer",
  "Senior Internal Auditor",
  "Senior Lawyer",
  "Senior Lecturer",
  "Senior Legal Counsel",
  "Senior Manager",
  "Senior Marketing Executive",
  "Senior Marketing Specialist",
  "Senior Mechanical Engineer",
  "Senior Medical Representative",
  "Senior Medical Sales Representative",
  "Senior Merchandiser",
  "Senior Network Engineer",
  "Senior Officer",
  "Senior Pharmacist",
  "Senior Physiotherapist",
  "Senior Planning Engineer",
  "Senior Process Engineer",
  "Senior Procurement Specialist",
  "Senior Product Designer",
  "Senior Product Manager",
  "Senior Product Specialist",
  "Senior Project Coordinator",
  "Senior Project Engineer",
  "Senior Project Manager",
  "Senior Property Consultant",
  "Senior Quantity Surveyor",
  "Senior Relationship Manager",
  "Senior Relationship Officer",
  "Senior Researcher",
  "Senior Sales",
  "Senior Sales Associate",
  "Senior Sales Consultant",
  "Senior Sales Engineer",
  "Senior Sales Executive",
  "Senior Sales Manager",
  "Senior Sales Representative",
  "Senior Site Engineer",
  "Senior Software Developer",
  "Senior Software Engineer",
  "Senior Structural Engineer",
  "Senior Supervisor",
  "Senior Surveyor",
  "Senior System Administrator",
  "Senior System Engineer",
  "Senior Talent Acquisition Specialist",
  "Senior Technician",
  "Senior Travel Consultant",
  "Senior Web Developer",
  "Serbest",
  "Server",
  "Serveur",
  "Service Advisor",
  "Service Crew",
  "Service Engineer",
  "Service Manager",
  "Service Technician",
  "Shift Engineer",
  "Shift Manager",
  "Shift Supervisor",
  "Shop Manager",
  "Showroom Manager",
  "Site Architect",
  "Site Civil Engineer",
  "Site Engineer",
  "Site Engineering",
  "Site Manager",
  "Site Supervisor",
  "Small Business Owner",
  "Social Media Coordinator",
  "Social Media Designer",
  "Social Media Manager",
  "Social Media Marketing Intern",
  "Social Media Marketing Manager",
  "Social Media Marketing Specialist",
  "Social Media Specialist",
  "Social Worker",
  "Software Architect",
  "Software Developer",
  "Software Development Engineer",
  "Software Development Intern",
  "Software Development Team Lead",
  "Software Engineer",
  "Software Engineer Intern",
  "Software Programmer",
  "Software Specialist",
  "Software Test Engineer",
  "Software Tester",
  "Soldier",
  "Solutions Architect",
  "Soudeur",
  "Sous Chef",
  "Spa Therapist",
  "Special Education Teacher",
  "Specialist",
  "Speech Language Pathologist",
  "Sports Coach",
  "Staff",
  "Staff Accountant",
  "Staff Nurse",
  "Staff Registered Nurse",
  "Stage",
  "Stage PFE",
  "Stage d'initiation",
  "Stage d'observation",
  "Stagiaire",
  "Stagiaire comptable",
  "Stagiaire projet",
  "Staj",
  "Stajer",
  "Stajyer",
  "Stajyer Avukat",
  "Stajyer Diyetisyen",
  "Stajyer Fizyoterapist",
  "Stajyer Mimar",
  "Stajyer Psikolog",
  "Steward",
  "Stock Controller",
  "Store Assistant",
  "Store Cashier",
  "Store Incharge",
  "Store Manager",
  "Store Supervisor",
  "Storekeeper",
  "Structural Design Engineer",
  "Structural Engineer",
  "Student",
  "Student Assistant",
  "Student Intern",
  "Student Internship",
  "Student Trainee",
  "Subject Matter Expert",
  "Summer Intern",
  "Summer Internship",
  "Summer Trainee",
  "Superviseur",
  "Superviseur HSE",
  "Superviseur commercial",
  "Superviseur/chef de bureau",
  "Supervisor",
  "Supply Chain Intern",
  "Supply Chain Manager",
  "Supply Chain Specialist",
  "Support Engineer",
  "Support Specialist",
  "Survey Engineer",
  "Surveyor",
  "Sushi Chef",
  "Swimming Coach",
  "System Administrator",
  "System Analyst",
  "System Engineer",
  "Systems Engineer",
  "Tailor",
  "Talent Acquisition Specialist",
  "Tax Accountant",
  "Taxi Driver",
  "Teacher",
  "Teacher Assistant",
  "Teacher of English",
  "Teaching Assistant",
  "Teaching Professional",
  "Team Lead",
  "Team Lead Manager",
  "Team Leader",
  "Team Manager",
  "Team Member",
  "Team Supervisor",
  "Team leader",
  "Technical Architect",
  "Technical Assistant",
  "Technical Consultant",
  "Technical Director",
  "Technical Engineer",
  "Technical Expert",
  "Technical Lead",
  "Technical Manager",
  "Technical Office Engineer",
  "Technical Office Manager",
  "Technical Project Manager",
  "Technical Sales Engineer",
  "Technical Specialist",
  "Technical Supervisor",
  "Technical Support",
  "Technical Support Engineer",
  "Technical Support Manager",
  "Technical Support Representative",
  "Technical Support Specialist",
  "Technical Team Lead",
  "Technician",
  "Technicien",
  "Technicien informatique",
  "Technicien maintenance",
  "Teknik Ressam",
  "Tekniker",
  "Teknisyen",
  "Tekstil",
  "Telecommunications Engineer",
  "Telecommunications Technician",
  "Telemarketer",
  "Telephone Operator",
  "Telesales Agent",
  "Telesales Representative",
  "Telesales Specialist",
  "Teller",
  "Territory Manager",
  "Territory Sales Manager",
  "Test Engineer",
  "Tour Guide",
  "Tour Operator",
  "Trader",
  "Trainee",
  "Trainee Engineer",
  "Trainee Lawyer",
  "Trainee lawyer",
  "Trainer",
  "Training",
  "Training Coordinator",
  "Training Manager",
  "Training Specialist",
  "Translator",
  "Travel Agent",
  "Travel Consultant",
  "Treasurer",
  "Treasury Accountant",
  "Truck Driver",
  "Turizm",
  "Tutor",
  "Typist",
  "UI Designer",
  "UI/UX Designer",
  "UX Designer",
  "UX/UI Designer",
  "Undergraduate Research Assistant",
  "Unemployed",
  "Unit Manager",
  "University Lecturer",
  "Urban Planner",
  "User Experience Designer",
  "Usher",
  "Usta",
  "Uzman",
  "Vendeur",
  "Vendeuse",
  "Ventes",
  "Veterinarian",
  "Vice President",
  "Video Editor",
  "Videographer",
  "Virtual Assistant",
  "Visiting Lecturer",
  "Visiting Researcher",
  "Visual Merchandiser",
  "Voice Over Artist",
  "Volunteer",
  "Waiter",
  "Waitress",
  "Warehouse Assistant",
  "Warehouse Associate",
  "Warehouse Manager",
  "Warehouse Specialist",
  "Warehouse Supervisor",
  "Web Designer",
  "Web Developer",
  "Web Development Intern",
  "Webmaster",
  "Welder",
  "Welding Inspector",
  "Wordpress Developer",
  "Worker",
  "Workshop Manager",
  "Workshop Supervisor",
  "Writer",
  "Yazar",
  "Yetkili",
  "Yok",
  "account",
  "accountant",
  "accounting",
  "admin",
  "administrateur",
  "architect",
  "architecte",
  "avukat",
  "business",
  "cadre",
  "cashier",
  "ceo",
  "chef",
  "chemist",
  "civil engineer",
  "commercial",
  "comptable",
  "consultant",
  "customer service",
  "dentist",
  "designer",
  "directeur",
  "director",
  "doctor",
  "doktor",
  "dr",
  "driver",
  "electrical engineer",
  "emekli",
  "employee",
  "eng",
  "engineer",
  "enseignant",
  "enseignante",
  "esnaf",
  "fonctionnaire",
  "free",
  "garson",
  "general manager",
  "gerant",
  "graphic designer",
  "iOS Developer",
  "ingenieur",
  "intern",
  "it",
  "journalist",
  "kasiyer",
  "lawyer",
  "lecturer",
  "manager",
  "managing director",
  "maneger",
  "manger",
  "marketing",
  "marketing manager",
  "mechanical engineer",
  "medecin",
  "memur",
  "mimar",
  "muhasebe",
  "no",
  "none",
  "nurse",
  "owner",
  "patron",
  "pazarlama",
  "pharmacist",
  "prof",
  "professeur",
  "professor",
  "programmer",
  "project manager",
  "researcher",
  "rien",
  "sales",
  "sales executive",
  "sales man",
  "sales manager",
  "salesman",
  "secretary",
  "sekreter",
  "serbest",
  "site engineer",
  "staff nurse",
  "stage",
  "stagiaire",
  "stajer",
  "stajyer",
  "student",
  "supervisor",
  "teacher",
  "technician",
  "technicien",
  "tekniker",
  "teknisyen",
  "tekstil",
  "trainee",
  "translator",
  "usta",
  "uzman",
  "waiter",
  "yok"
];
