export const SPECIALTIES = [
  { id: "Defense & Space", title: "Defense & Space" },
  { id: "Computer Hardware", title: "Computer Hardware" },
  { id: "Computer Software", title: "Computer Software" },
  { id: "Computer Networking", title: "Computer Networking" },
  { id: "Internet", title: "Internet" },
  { id: "Semiconductors", title: "Semiconductors" },
  { id: "Telecommunications", title: "Telecommunications" },
  { id: "Law Practice", title: "Law Practice" },
  { id: "Legal Services", title: "Legal Services" },
  { id: "Management Consulting", title: "Management Consulting" },
  { id: "Biotechnology", title: "Biotechnology" },
  { id: "Medical Practice", title: "Medical Practice" },
  { id: "Hospital & Health Care", title: "Hospital & Health Care" },
  { id: "Pharmaceuticals", title: "Pharmaceuticals" },
  { id: "Veterinary", title: "Veterinary" },
  { id: "Medical Device", title: "Medical Device" },
  { id: "Cosmetics", title: "Cosmetics" },
  { id: "Apparel & Fashion", title: "Apparel & Fashion" },
  { id: "Sporting Goods", title: "Sporting Goods" },
  { id: "Supermarkets", title: "Supermarkets" },
  { id: "Food Production", title: "Food Production" },
  { id: "Consumer Electronics", title: "Consumer Electronics" },
  { id: "Consumer Goods", title: "Consumer Goods" },
  { id: "Furniture", title: "Furniture" },
  { id: "Retail", title: "Retail" },
  { id: "Entertainment", title: "Entertainment" },
  { id: "Leisure, Travel & Tourism", title: "Leisure, Travel & Tourism" },
  { id: "Hospitality", title: "Hospitality" },
  { id: "Restaurants", title: "Restaurants" },
  { id: "Sports", title: "Sports" },
  { id: "Food & Beverages", title: "Food & Beverages" },
  { id: "Motion Pictures & Film", title: "Motion Pictures & Film" },
  { id: "Broadcast Media", title: "Broadcast Media" },
  { id: "Museums & Institutions", title: "Museums & Institutions" },
  { id: "Fine Art", title: "Fine Art" },
  { id: "Performing Arts", title: "Performing Arts" },
  { id: "Recreational Facilities & Services", title: "Recreational Facilities & Services" },
  { id: "Banking", title: "Banking" },
  { id: "Insurance", title: "Insurance" },
  { id: "Financial Services", title: "Financial Services" },
  { id: "Real Estate", title: "Real Estate" },
  { id: "Investment Banking", title: "Investment Banking" },
  { id: "Investment Management", title: "Investment Management" },
  { id: "Accounting", title: "Accounting" },
  { id: "Construction", title: "Construction" },
  { id: "Building Materials", title: "Building Materials" },
  { id: "Architecture & Planning", title: "Architecture & Planning" },
  { id: "Civil Engineering", title: "Civil Engineering" },
  { id: "Aviation & Aerospace", title: "Aviation & Aerospace" },
  { id: "Automotive", title: "Automotive" },
  { id: "Chemicals", title: "Chemicals" },
  { id: "Machinery", title: "Machinery" },
  { id: "Mining & Metals", title: "Mining & Metals" },
  { id: "Oil & Energy", title: "Oil & Energy" },
  { id: "Shipbuilding", title: "Shipbuilding" },
  { id: "Utilities", title: "Utilities" },
  { id: "Textiles", title: "Textiles" },
  { id: "Paper & Forest Products", title: "Paper & Forest Products" },
  { id: "Railroad Manufacture", title: "Railroad Manufacture" },
  { id: "Farming", title: "Farming" },
  { id: "Ranching", title: "Ranching" },
  { id: "Dairy", title: "Dairy" },
  { id: "Fishery", title: "Fishery" },
  { id: "Primary/Secondary Education", title: "Primary/Secondary Education" },
  { id: "Higher Education", title: "Higher Education" },
  { id: "Education Management", title: "Education Management" },
  { id: "Research", title: "Research" },
  { id: "Military", title: "Military" },
  { id: "Legislative Office", title: "Legislative Office" },
  { id: "Judiciary", title: "Judiciary" },
  { id: "International Affairs", title: "International Affairs" },
  { id: "Government Administration", title: "Government Administration" },
  { id: "Executive Office", title: "Executive Office" },
  { id: "Law Enforcement", title: "Law Enforcement" },
  { id: "Public Safety", title: "Public Safety" },
  { id: "Public Policy", title: "Public Policy" },
  { id: "Marketing & Advertising", title: "Marketing & Advertising" },
  { id: "Newspapers", title: "Newspapers" },
  { id: "Publishing", title: "Publishing" },
  { id: "Printing", title: "Printing" },
  { id: "Information Services", title: "Information Services" },
  { id: "Libraries", title: "Libraries" },
  { id: "Environmental Services", title: "Environmental Services" },
  { id: "Package/Freight Delivery", title: "Package/Freight Delivery" },
  { id: "Individual & Family Services", title: "Individual & Family Services" },
  { id: "Religious Institutions", title: "Religious Institutions" },
  { id: "Civic & Social Organization", title: "Civic & Social Organization" },
  { id: "Consumer Services", title: "Consumer Services" },
  { id: "Transportation/Trucking/Railroad", title: "Transportation/Trucking/Railroad" },
  { id: "Warehousing", title: "Warehousing" },
  { id: "Airlines/Aviation", title: "Airlines/Aviation" },
  { id: "Maritime", title: "Maritime" },
  { id: "Information Technology & Services", title: "Information Technology & Services" },
  { id: "Market Research", title: "Market Research" },
  { id: "Public Relations & Communications", title: "Public Relations & Communications" },
  { id: "Design", title: "Design" },
  { id: "Non-profit Organization Management", title: "Non-profit Organization Management" },
  { id: "Fundraising", title: "Fundraising" },
  { id: "Program Development", title: "Program Development" },
  { id: "Writing & Editing", title: "Writing & Editing" },
  { id: "Staffing & Recruiting", title: "Staffing & Recruiting" },
  { id: "Professional Training & Coaching", title: "Professional Training & Coaching" },
  { id: "Venture Capital & Private Equity", title: "Venture Capital & Private Equity" },
  { id: "Political Organization", title: "Political Organization" },
  { id: "Translation & Localization", title: "Translation & Localization" },
  { id: "Computer Games", title: "Computer Games" },
  { id: "Events Services", title: "Events Services" },
  { id: "Arts & Crafts", title: "Arts & Crafts" },
  { id: "Electrical & Electronic Manufacturing", title: "Electrical & Electronic Manufacturing" },
  { id: "Online Media", title: "Online Media" },
  { id: "Nanotechnology", title: "Nanotechnology" },
  { id: "Logistics & Supply Chain", title: "Logistics & Supply Chain" },
  { id: "Plastics", title: "Plastics" },
  { id: "Computer & Network Security", title: "Computer & Network Security" },
  { id: "Wireless", title: "Wireless" },
  { id: "Alternative Dispute Resolution", title: "Alternative Dispute Resolution" },
  { id: "Security & Investigations", title: "Security & Investigations" },
  { id: "Facilities Services", title: "Facilities Services" },
  { id: "Outsourcing/Offshoring", title: "Outsourcing/Offshoring" },
  { id: "Health, Wellness & Fitness", title: "Health, Wellness & Fitness" },
  { id: "Alternative Medicine", title: "Alternative Medicine" },
  { id: "Media Production", title: "Media Production" },
  { id: "Animation", title: "Animation" },
  { id: "Commercial Real Estate", title: "Commercial Real Estate" },
  { id: "Capital Markets", title: "Capital Markets" },
  { id: "Think Tanks", title: "Think Tanks" },
  { id: "Philanthropy", title: "Philanthropy" },
  { id: "E-learning", title: "E-learning" },
  { id: "Wholesale", title: "Wholesale" },
  { id: "Import & Export", title: "Import & Export" },
  { id: "Mechanical Or Industrial Engineering", title: "Mechanical Or Industrial Engineering" },
  { id: "Photography", title: "Photography" },
  { id: "Human Resources", title: "Human Resources" },
  { id: "Business Supplies & Equipment", title: "Business Supplies & Equipment" },
  { id: "Mental Health Care", title: "Mental Health Care" },
  { id: "Graphic Design", title: "Graphic Design" },
  { id: "International Trade & Development", title: "International Trade & Development" },
  { id: "Luxury Goods & Jewelry", title: "Luxury Goods & Jewelry" },
  { id: "Renewables & Environment", title: "Renewables & Environment" },
  { id: "Glass, Ceramics & Concrete", title: "Glass, Ceramics & Concrete" },
  { id: "Packaging & Containers", title: "Packaging & Containers" },
  { id: "Industrial Automation", title: "Industrial Automation" },
  { id: "Government Relations", title: "Government Relations" }
];
